# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  actuator2_to_actuator1:
    has_velocity_limits: true
    max_velocity: 100.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  actuator3_to_upperarm_link:
    has_velocity_limits: true
    max_velocity: 100.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  actuator4_to_forearm_link:
    has_velocity_limits: true
    max_velocity: 100.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  gripper_left_joint:
    has_velocity_limits: true
    max_velocity: 4.7999999999999998
    has_acceleration_limits: false
    max_acceleration: 0.0
  gripper_right_joint:
    has_velocity_limits: true
    max_velocity: 4.7999999999999998
    has_acceleration_limits: false
    max_acceleration: 0.0
  upperarm_link_to_actuator2:
    has_velocity_limits: true
    max_velocity: 100.0
    
    has_acceleration_limits: false
    max_acceleration: 0.0